#!/bin/bash

gmt_headers()
{
	local src="$1"

	for header in $(
		egrep '^\s*#include\s+<gmt.*$' "$src" |
		sed -r 's/\s*#include\s+<([^>]+)>/\1/'
	)
	do
		echo "../$header"
	done
}

CMAKELISTS_HEADER=\
"# generated by generate-cmakelists.sh
cmake_minimum_required (VERSION 3.0)
project (gmt-examples)

# export information about compilation
set(CMAKE_EXPORT_COMPILE_COMMANDS "ON")

include_directories(..)

find_package(OpenGL REQUIRED)
find_package(glfw3 REQUIRED)
find_package(OpenCV REQUIRED)
"

echo "${CMAKELISTS_HEADER}"

for src in ./*.cpp
do

	headers=$(gmt_headers "$src")
	base="$(basename $src)"
	exe="${base%.cpp}"
	echo "add_executable("

	for i in $exe "$src" $headers
	do
		echo -e "\t$i"
	done

	echo ")"
	echo "target_link_libraries($exe \${OPENGL_gl_LIBRARY} glfw \${OpenCV_LIBS})"
	echo
done
