#!/bin/bash

CMAKELISTS_HEADER=\
"# generated by generate-cmakelists.sh
cmake_minimum_required (VERSION 3.0)
project (gmt-examples)
include_directories(..)

find_package(OpenGL REQUIRED)
find_package(glfw3 REQUIRED)
find_package(OpenCV REQUIRED)
"

echo "${CMAKELISTS_HEADER}"

for src in ./*.cpp
do
	base="$(basename $src)"
	exe="${base%.cpp}"
	echo "add_executable($exe $src)"
	echo "target_link_libraries($exe \${OPENGL_gl_LIBRARY} glfw \${OpenCV_LIBS})"
	echo
done
